### ISSUE TITLE
Not supporting with Swift 5.0 version

### ISSUE THREAD

**Issue by vijay2pvk** [DiUS/pact-consumer-swift#47] opened 2019-04-03 07:59 UTC
I am not able to update the carthage with Swift 5.0 (XCode 10.2).

error: compiling for iOS 9.0, but module 'Alamofire' has a minimum deployment target of iOS 10.0: $(SRCROOT)/Carthage/Checkouts/pact-consumer-swift/Carthage/Build/iOS/Alamofire.framework/Modules/Alamofire.swiftmodule/armv7.swiftmodule
import Alamofire
       ^

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by surpher** [comment] 2019-04-03 22:05
Thanks for reporting it. We'll bump up the dependencies versions and submit a new version asap.

Actually, we'll have to look into removing Alamofire altogether to avoid these unsupported versions. 

In the mean time, to get around this I suppose you could go into your /Carthage folder, find the Alamofire version declaration that's not supporting your iOS 9.0 minimum supported project and replace it with a version that does.

**Comment by andrewspinks** [comment] 2019-04-07 08:13
@vijay2pvk I just created a new project in XCode 10.2 using Swift 5.0, Carthage and the deployment target set to iOS 9.0 but I could not reproduce the same issue. Can you give any more information about your build settings? Also, it might be worth playing with the iOS deployment target settings to see if that is causing the build failures.

**Comment by andrewspinks** [comment] 2019-06-06 07:02
Closing as couldn't reproduce. We can re-open the issue if you continue to have problems.

**Closed as completed by andrewspinks** 2019-06-06 07:02 UTC
